version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'

  webpack:
    container_name: htmx-test-webpack
    environment:
      - NODE_ENV=development
    image: htmx-test/webpack
    ports:
      - '3000:3000'
    build:
      context: ./webpack
    command: "npm run dev"
    volumes:
      - "./webpack:/webpack"
      - "./web:/web"
